FROM rockylinux/rockylinux:9@sha256:8101994123cf3d0a8fee517bee7f39e555c7d92bd2d9eb3303cc988a0eeed00f
RUN dnf install -y systemd dbus openssl shadow-utils curl-minimal && dnf clean all
CMD ["/usr/sbin/init"]
