FROM scratch

ARG TARGETPLATFORM
ARG TAG
ARG SOURCE

LABEL name="SILO Console" \
      maintainer="Pigsty" \
      version="${TAG}" \
      release="${TAG}" \
      summary="The SILO object storage console" \
      description="See Github for more information https://github.com/pgsty/silo-console" \
      org.opencontainers.image.source="https://github.com/pgsty/silo-console" \
      org.opencontainers.image.description="The SILO object storage console" \
      org.opencontainers.image.licenses="AGPL-3.0-or-later"

COPY $TARGETPLATFORM/silo-console /console
COPY LICENSE NOTICE CREDITS /usr/share/licenses/silo-console/

EXPOSE 9090

USER 1000:1000
ENTRYPOINT ["/console"]
CMD ["server"]
