// Code generated by go-swagger; DO NOT EDIT.

// This file is part of Console Server
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

package user

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/minio/console/models"
)

// UpdateUserInfoLegacyHandlerFunc turns a function with the right signature into a update user info legacy handler
type UpdateUserInfoLegacyHandlerFunc func(UpdateUserInfoLegacyParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateUserInfoLegacyHandlerFunc) Handle(params UpdateUserInfoLegacyParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// UpdateUserInfoLegacyHandler interface for that can handle valid update user info legacy params
type UpdateUserInfoLegacyHandler interface {
	Handle(UpdateUserInfoLegacyParams, *models.Principal) middleware.Responder
}

// NewUpdateUserInfoLegacy creates a new http.Handler for the update user info legacy operation
func NewUpdateUserInfoLegacy(ctx *middleware.Context, handler UpdateUserInfoLegacyHandler) *UpdateUserInfoLegacy {
	return &UpdateUserInfoLegacy{Context: ctx, Handler: handler}
}

/*
	UpdateUserInfoLegacy swagger:route PUT /user/{name} User updateUserInfoLegacy

Update User Info (Deprecated)

Deprecated compatibility endpoint. Use /user/{name}/status and /user/{name}/groups for independent updates.
*/
type UpdateUserInfoLegacy struct {
	Context *middleware.Context
	Handler UpdateUserInfoLegacyHandler
}

func (o *UpdateUserInfoLegacy) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdateUserInfoLegacyParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
