// This file is part of MinIO Console Server
// Copyright (c) 2026 MinIO, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// Command credits regenerates and verifies CREDITS, the third-party license
// inventory shipped inside every Console artifact.
//
// The Go section is the union of the modules linked into ./cmd/console for
// every release target (linux, darwin and windows on the release
// architectures), so a notice needed by one platform's binary is present in
// all of them. Every legal file at a module root that matches an explicit
// filename policy is included verbatim; a module with none must be listed in
// hack/credits/exceptions.json with vendored text, otherwise the run fails.
// Replaced modules are credited under the import path with the fork that
// provides them, using the fork's own license and notice files.
//
// The frontend section is produced by hack/credits/frontend.mjs from the
// production dependency closure in web-app/node_modules plus the bundled font
// families listed in web-app/licenses/fonts.json.
//
// Usage:
//
//	go run ./hack/credits check --go        # Go section matches CREDITS (make verifiers)
//	go run ./hack/credits check --frontend  # frontend section matches (needs web-app/node_modules)
//	go run ./hack/credits update            # regenerate both sections
//	go run ./hack/credits update --go       # regenerate the Go section only
package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

const (
	creditsPath    = "CREDITS"
	exceptionsPath = "hack/credits/exceptions.json"
	stdlibTextPath = "hack/credits/texts/go-stdlib.txt"
	frontendScript = "hack/credits/frontend.mjs"
	mainPackage    = "./cmd/console"
	buildTags      = "kqueue,operator"

	separator        = "================================================================"
	fileSeparator    = "----------------------------------------------------------------"
	goSectionMarker  = "==== Go modules linked into the Console binary ===="
	feSectionMarker  = "==== Frontend runtime bundled into web-app/build ===="
	headerLine       = "SILO Console third-party notices"
	generatedByLine  = "Generated by `go run ./hack/credits update`; verified by `make verifiers` (Go section) and by the frontend check in CI. Do not edit by hand."
	replacedIntroTxt = "The shipped binary satisfies these upstream import paths from PGSTY-maintained forks (go.mod replace directives); each is credited below under its import path with the fork's own license and notice files:"
)

// releaseTargets mirrors .goreleaser.yml.
var releaseTargets = []struct{ goos, goarch string }{
	{"linux", "amd64"},
	{"linux", "arm64"},
	{"linux", "arm"},
	{"darwin", "amd64"},
	{"darwin", "arm64"},
	{"windows", "amd64"},
}

var (
	legalStems = []string{"LICENSE", "LICENCE", "COPYING", "UNLICENSE", "NOTICE"} //nolint:misspell // LICENCE is the British spelling some modules use
	// source and data extensions never carry a license text on their own
	sourceExtensions = map[string]bool{
		"go": true, "py": true, "js": true, "mjs": true, "cjs": true, "ts": true, "tsx": true, "jsx": true,
		"sh": true, "rs": true, "c": true, "h": true, "cpp": true, "cc": true, "java": true, "rb": true, "php": true, "pl": true,
		"yaml": true, "yml": true, "json": true, "toml": true, "xml": true, "html": true, "css": true, "proto": true, "s": true,
	}
	legalSuffix = regexp.MustCompile(`^[.-]([A-Za-z0-9]+)$`)
)

type moduleInfo struct {
	Path    string
	Version string
	Dir     string
	Replace *moduleInfo
	Main    bool
}

type listedPackage struct {
	Standard bool
	Module   *moduleInfo
}

type exception struct {
	License   string `json:"license"`
	Copyright string `json:"copyright"`
	Source    string `json:"source"`
	TextFile  string `json:"text_file"`
}

func main() {
	if err := run(os.Args[1:]); err != nil {
		fmt.Fprintf(os.Stderr, "credits: %v\n", err)
		os.Exit(1)
	}
}

func run(args []string) error {
	if len(args) == 0 {
		return errors.New("usage: credits check|update [--go] [--frontend]")
	}
	mode := args[0]
	doGo, doFrontend := false, false
	for _, flag := range args[1:] {
		switch flag {
		case "--go":
			doGo = true
		case "--frontend":
			doFrontend = true
		default:
			return fmt.Errorf("unknown flag %q", flag)
		}
	}
	if !doGo && !doFrontend {
		doGo, doFrontend = true, true
	}
	if err := requireRepositoryRoot(); err != nil {
		return err
	}

	existing, _ := os.ReadFile(creditsPath)
	current := splitSections(string(existing))

	goSection, feSection := current.goSection, current.feSection
	if doGo {
		generated, err := generateGoSection()
		if err != nil {
			return err
		}
		goSection = generated
	}
	if doFrontend {
		generated, err := generateFrontendSection()
		if err != nil {
			return err
		}
		feSection = generated
	}
	rendered := render(goSection, feSection)

	switch mode {
	case "update":
		return os.WriteFile(creditsPath, []byte(rendered), 0o644)
	case "check":
		if rendered != string(existing) {
			return fmt.Errorf("%s is stale for the requested section(s); run `go run ./hack/credits update` and commit the result (%s)", creditsPath, firstDifference(string(existing), rendered))
		}
		fmt.Printf("credits: %s is up to date\n", creditsPath)
		return nil
	default:
		return fmt.Errorf("unknown mode %q (want check or update)", mode)
	}
}

func requireRepositoryRoot() error {
	out, err := exec.Command("go", "list", "-m").Output()
	if err != nil || strings.TrimSpace(string(out)) != "github.com/minio/console" {
		return errors.New("run from the Console repository root")
	}
	return nil
}

type sections struct{ goSection, feSection string }

// splitSections extracts the two generated sections from an existing CREDITS
// so one can be regenerated while the other is kept verbatim.
func splitSections(credits string) sections {
	var s sections
	goStart := strings.Index(credits, goSectionMarker)
	feStart := strings.Index(credits, feSectionMarker)
	if goStart >= 0 {
		end := len(credits)
		if feStart > goStart {
			end = feStart
		}
		s.goSection = strings.TrimPrefix(credits[goStart:end], goSectionMarker+"\n\n")
	}
	if feStart >= 0 {
		s.feSection = strings.TrimPrefix(credits[feStart:], feSectionMarker+"\n\n")
	}
	return s
}

func render(goSection, feSection string) string {
	var sb strings.Builder
	sb.WriteString(headerLine + "\n" + strings.Repeat("=", len(headerLine)) + "\n\n")
	sb.WriteString(generatedByLine + "\n\n")
	sb.WriteString(goSectionMarker + "\n\n")
	sb.WriteString(goSection)
	sb.WriteString(feSectionMarker + "\n\n")
	sb.WriteString(feSection)
	return sb.String()
}

func firstDifference(a, b string) string {
	al, bl := strings.Split(a, "\n"), strings.Split(b, "\n")
	for i := 0; i < len(al) && i < len(bl); i++ {
		if al[i] != bl[i] {
			return fmt.Sprintf("first difference at line %d: have %q, want %q", i+1, al[i], bl[i])
		}
	}
	return fmt.Sprintf("line counts differ: have %d, want %d", len(al), len(bl))
}

// ---- Go section --------------------------------------------------------------

func generateGoSection() (string, error) {
	modules, err := linkedModules()
	if err != nil {
		return "", err
	}
	exceptions, err := loadExceptions()
	if err != nil {
		return "", err
	}
	stdlib, err := os.ReadFile(stdlibTextPath)
	if err != nil {
		return "", fmt.Errorf("standard library credit text: %w", err)
	}

	paths := make([]string, 0, len(modules))
	for path := range modules {
		paths = append(paths, path)
	}
	sort.Strings(paths)

	var sb strings.Builder
	var replaced []string
	for _, path := range paths {
		if m := modules[path]; m.Replace != nil && m.Replace.Path != m.Path {
			replaced = append(replaced, fmt.Sprintf("  %s => %s %s", m.Path, m.Replace.Path, m.Replace.Version))
		}
	}
	if len(replaced) > 0 {
		sb.WriteString(replacedIntroTxt + "\n" + strings.Join(replaced, "\n") + "\n\n" + separator + "\n\n")
	}
	sb.WriteString(strings.TrimRight(string(stdlib), "\n") + "\n\n" + separator + "\n\n")

	var problems []string
	for _, path := range paths {
		m := modules[path]
		entry, err := moduleEntry(m, exceptions)
		if err != nil {
			problems = append(problems, err.Error())
			continue
		}
		sb.WriteString(entry + "\n" + separator + "\n\n")
	}
	for path := range exceptions {
		if _, linked := modules[path]; !linked {
			problems = append(problems, fmt.Sprintf("%s: exception is stale, the module is no longer linked", path))
		}
	}
	if len(problems) > 0 {
		sort.Strings(problems)
		return "", errors.New("Go credits are incomplete:\n  - " + strings.Join(problems, "\n  - "))
	}
	return sb.String(), nil
}

// linkedModules unions the non-standard modules that reach the binary on every
// release target.
func linkedModules() (map[string]*moduleInfo, error) {
	modules := map[string]*moduleInfo{}
	for _, target := range releaseTargets {
		cmd := exec.Command("go", "list", "-deps", "-json=Standard,Module", "-tags", buildTags, mainPackage)
		cmd.Env = append(os.Environ(), "GOOS="+target.goos, "GOARCH="+target.goarch, "CGO_ENABLED=0")
		var stderr bytes.Buffer
		cmd.Stderr = &stderr
		out, err := cmd.Output()
		if err != nil {
			return nil, fmt.Errorf("go list for %s/%s: %v\n%s", target.goos, target.goarch, err, stderr.String())
		}
		decoder := json.NewDecoder(bytes.NewReader(out))
		for {
			var pkg listedPackage
			if err := decoder.Decode(&pkg); err != nil {
				if errors.Is(err, os.ErrClosed) || err.Error() == "EOF" {
					break
				}
				return nil, fmt.Errorf("parse go list output: %w", err)
			}
			if pkg.Standard || pkg.Module == nil || pkg.Module.Main {
				continue
			}
			if _, seen := modules[pkg.Module.Path]; !seen {
				modules[pkg.Module.Path] = pkg.Module
			}
		}
	}
	return modules, nil
}

func loadExceptions() (map[string]exception, error) {
	raw, err := os.ReadFile(exceptionsPath)
	if err != nil {
		return nil, err
	}
	var decoded map[string]json.RawMessage
	if err := json.Unmarshal(raw, &decoded); err != nil {
		return nil, fmt.Errorf("%s: %w", exceptionsPath, err)
	}
	exceptions := map[string]exception{}
	for path, message := range decoded {
		if strings.HasPrefix(path, "_") {
			continue
		}
		var e exception
		if err := json.Unmarshal(message, &e); err != nil {
			return nil, fmt.Errorf("%s: %s: %w", exceptionsPath, path, err)
		}
		if e.TextFile == "" || e.License == "" {
			return nil, fmt.Errorf("%s: %s needs license and text_file", exceptionsPath, path)
		}
		exceptions[path] = e
	}
	return exceptions, nil
}

func moduleEntry(m *moduleInfo, exceptions map[string]exception) (string, error) {
	effective := m
	if m.Replace != nil {
		effective = m.Replace
	}
	if effective.Dir == "" {
		return "", fmt.Errorf("%s: module directory unknown (run `go mod download` first)", m.Path)
	}
	files, err := legalFiles(effective.Dir)
	if err != nil {
		return "", fmt.Errorf("%s: %w", m.Path, err)
	}

	var sb strings.Builder
	if m.Replace != nil && m.Replace.Path != m.Path {
		fmt.Fprintf(&sb, "%s (provided by %s %s)\nhttps://%s\n", m.Path, m.Replace.Path, m.Replace.Version, m.Replace.Path)
	} else {
		fmt.Fprintf(&sb, "%s\nhttps://%s\n", m.Path, m.Path)
	}
	sb.WriteString(fileSeparator + "\n")

	if e, ok := exceptions[m.Path]; ok {
		if len(files) > 0 {
			return "", fmt.Errorf("%s: exception is stale, the module now ships %s", m.Path, strings.Join(files, ", "))
		}
		text, err := os.ReadFile(e.TextFile)
		if err != nil {
			return "", fmt.Errorf("%s: exception text: %w", m.Path, err)
		}
		fmt.Fprintf(&sb, "License: %s (%s)\n\n%s\n", e.License, e.Source, normalizeText(text))
		return sb.String(), nil
	}
	if len(files) == 0 {
		return "", fmt.Errorf("%s: no legal file at the module root and no entry in %s", m.Path, exceptionsPath)
	}
	for i, name := range files {
		text, err := os.ReadFile(filepath.Join(effective.Dir, name))
		if err != nil {
			return "", fmt.Errorf("%s: %w", m.Path, err)
		}
		if len(files) > 1 {
			if i > 0 {
				sb.WriteString("\n")
			}
			fmt.Fprintf(&sb, "-- %s --\n", name)
		}
		sb.WriteString(normalizeText(text) + "\n")
	}
	return sb.String(), nil
}

// legalFiles returns the module-root files that carry license or notice text,
// under an explicit policy: a known stem (LICENSE, its British spelling,
// COPYING, UNLICENSE, NOTICE), alone or followed by "." or "-" and one
// alphanumeric word that is not a source or data extension. Case-insensitive;
// sorted.
func legalFiles(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	var files []string
	for _, entry := range entries {
		if entry.IsDir() || !isLegalFileName(entry.Name()) {
			continue
		}
		files = append(files, entry.Name())
	}
	sort.Strings(files)
	return files, nil
}

func isLegalFileName(name string) bool {
	upper := strings.ToUpper(name)
	for _, stem := range legalStems {
		if !strings.HasPrefix(upper, stem) {
			continue
		}
		rest := name[len(stem):]
		if rest == "" {
			return true
		}
		match := legalSuffix.FindStringSubmatch(rest)
		if match == nil {
			return false
		}
		return !sourceExtensions[strings.ToLower(match[1])]
	}
	return false
}

func normalizeText(text []byte) string {
	s := strings.ReplaceAll(string(text), "\r\n", "\n")
	s = strings.TrimRight(s, "\n\t ")
	lines := strings.Split(s, "\n")
	for i, line := range lines {
		lines[i] = strings.TrimRight(line, " \t")
	}
	return strings.Join(lines, "\n")
}

// ---- Frontend section --------------------------------------------------------

func generateFrontendSection() (string, error) {
	if _, err := os.Stat(filepath.Join("web-app", "node_modules")); err != nil {
		return "", errors.New("web-app/node_modules is missing; run `yarn install --immutable` in web-app before the frontend credits check")
	}
	cmd := exec.Command("node", frontendScript)
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	out, err := cmd.Output()
	if err != nil {
		return "", fmt.Errorf("%s: %v\n%s", frontendScript, err, stderr.String())
	}
	return string(out), nil
}
